root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/tcp-server"
  cmd = "go build -o ./tmp/tcp-server ./cmd/tcp-server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_pb.go"]
  include_ext = ["go"]
  kill_delay = "2s"
  log = "tcp-build-errors.log"
  send_interrupt = true

[color]
  app = "red"
  build = "yellow"
  main = "magenta"  
  runner = "green"
  watcher = "cyan"

[log]
  time = true
