-- -- Focus on relationships that support all use cases
-- CREATE TABLE users (
--     id TEXT PRIMARY KEY,
--     username TEXT UNIQUE NOT NULL,
--     password_hash TEXT NOT NULL,
--     email TEXT UNIQUE NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE manga (
--     id TEXT PRIMARY KEY,
--     title TEXT NOT NULL,
--     author TEXT,
--     genres TEXT,  -- JSON array for flexibility
--     status TEXT CHECK(status IN ('ongoing', 'completed', 'hiatus')),
--     total_chapters INTEGER,
--     description TEXT,
--     cover_url TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE user_progress (
--     user_id TEXT,
--     manga_id TEXT,
--     current_chapter INTEGER DEFAULT 0,
--     status TEXT CHECK(status IN ('reading', 'completed', 'plan_to_read', 'dropped')),
--     rating INTEGER CHECK(rating >= 1 AND rating <= 10),
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (user_id, manga_id),
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
--     FOREIGN KEY (manga_id) REFERENCES manga(id) ON DELETE CASCADE
-- );
